config/routes.rb
RestApiCostumeContest::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :contests, only: [:index, :show] do
        resources :categories, only: [:index, :show]
      end
    end
  end

  resources :entries

  resources :categories

  resources :category_descriptions

  resources :contests

end

app/models/category_description.rb
class CategoryDescription < ActiveRecord::Base
  has_many :categories
end

app/controllers/category_descriptions_controller.rb
class CategoryDescriptionsController < ApplicationController
  before_action :set_category_description, only: [:show, :edit, :update, :destroy]

  # GET /category_descriptions
  # GET /category_descriptions.json
  def index
    @category_descriptions = CategoryDescription.all
  end

  # GET /category_descriptions/1
  # GET /category_descriptions/1.json
  def show
  end

  # GET /category_descriptions/new
  def new
    @category_description = CategoryDescription.new
  end

  # GET /category_descriptions/1/edit
  def edit
  end

  # POST /category_descriptions
  # POST /category_descriptions.json
  def create
    @category_description = CategoryDescription.new(category_description_params)

    respond_to do |format|
      if @category_description.save
        format.html { redirect_to @category_description, notice: 'Category description was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category_description }
      else
        format.html { render action: 'new' }
        format.json { render json: @category_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_descriptions/1
  # PATCH/PUT /category_descriptions/1.json
  def update
    respond_to do |format|
      if @category_description.update(category_description_params)
        format.html { redirect_to @category_description, notice: 'Category description was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_descriptions/1
  # DELETE /category_descriptions/1.json
  def destroy
    @category_description.destroy
    respond_to do |format|
      format.html { redirect_to category_descriptions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_description
      @category_description = CategoryDescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_description_params
      params.require(:category_description).permit(:name, :description)
    end
end

app/helpers/category_descriptions_helper.rb
module CategoryDescriptionsHelper
end

app/views/category_descriptions/_form.html.erb
<%= form_for(@category_description) do |f| %>
  <% if @category_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category_description.errors.count, "error") %> prohibited this category_description from being saved:</h2>

      <ul>
      <% @category_description.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/category_descriptions/edit.html.erb
<h1>Editing category_description</h1>

<%= render 'form' %>

<%= link_to 'Show', @category_description %> |
<%= link_to 'Back', category_descriptions_path %>

app/views/category_descriptions/index.html.erb
<h1>Listing category_descriptions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @category_descriptions.each do |category_description| %>
      <tr>
        <td><%= category_description.name %></td>
        <td><%= category_description.description %></td>
        <td><%= link_to 'Show', category_description %></td>
        <td><%= link_to 'Edit', edit_category_description_path(category_description) %></td>
        <td><%= link_to 'Destroy', category_description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category description', new_category_description_path %>

app/views/category_descriptions/new.html.erb
<h1>New category_description</h1>

<%= render 'form' %>

<%= link_to 'Back', category_descriptions_path %>

app/views/category_descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category_description.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category_description.description %>
</p>

<%= link_to 'Edit', edit_category_description_path(@category_description) %> |
<%= link_to 'Back', category_descriptions_path %>