config/routes.rb
RestApiCostumeContest::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :contests, only: [:index, :show] do
        resources :categories, only: [:index, :show]
      end
    end
  end

  resources :entries

  resources :categories

  resources :category_descriptions

  resources :contests

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_many :categories
end

app/controllers/api/v1/contests_controller.rb
module Api
  module V1
    class ContestsController < ApplicationController
      respond_to :json

      def index
        # respond_with Contest.all
        render json: Contest.all, each_serializer: ContestIndexSerializer
      end
      
      def show
        # respond_with Contest.find(params[:id])
        render json: Contest.find(params[:id])
      end

    end
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]

  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    @contest = Contest.find(params[:id])
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contest }
      else
        format.html { render action: 'new' }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:name, :description, :location, :contest_occurrence)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :contest_occurrence %><br>
    <%= f.datetime_select :contest_occurrence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<h1>Listing contests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Contest occurrence</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= contest.name %></td>
        <td><%= contest.description %></td>
        <td><%= contest.location %></td>
        <td><%= contest.contest_occurrence %></td>
        <td><%= link_to 'Show', contest %></td>
        <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
        <td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contest', new_contest_path %>

app/views/contests/new.html.erb
<h1>New contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contest.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contest.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @contest.location %>
</p>

<p>
  <strong>Contest occurrence:</strong>
  <%= @contest.contest_occurrence %>
</p>

<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>